name: Build eBook

# Workflow to build .epub and .mobi eBooks from the repository's markdown content
# This workflow uses the Python build script to assemble all sections and chapters
# into a complete book with table of contents and publishes it as a GitHub Release

on:
  # Allow manual triggering from GitHub Actions tab only
  workflow_dispatch:

# Set permissions for creating releases
permissions:
  contents: write

jobs:
  build-ebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        # Install required Python packages
        pip install PyYAML
        
        # Install Pandoc for epub generation
        sudo apt-get update
        sudo apt-get install -y pandoc
        
        # Install Calibre for mobi generation
        sudo apt-get install -y calibre
        
        # Verify installations
        python3 --version
        pandoc --version
        ebook-convert --version
    
    - name: Build eBook using Python script
      run: |
        # Create output directory
        mkdir -p dist
        
        # Run the Python build script
        python3 build_book.py dist
        
        # Verify output files
        ls -la dist/
        echo "Build completed successfully"
    
    - name: Generate release tag
      id: tag
      run: |
        # Generate a unique release tag based on current timestamp
        TAG="v$(date +%Y.%m.%d-%H%M%S)"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated release tag: $TAG"
    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: "Удивительный мир металлов ${{ steps.tag.outputs.tag }}"
        body: |
          📚 **Автоматически сгенерированная eBook версия "Удивительный мир металлов"**
          
          Эта книга создана из всех разделов и глав репозитория с автоматически сгенерированным содержанием.
          
          **Доступные форматы:**
          - 📖 **EPUB** - для большинства электронных книг и приложений
          - 📱 **MOBI** - для устройств Amazon Kindle
          
          **Содержание:**
          - Часть 1: История металлургии (8 глав)
          - Часть 2: Основы металлургии (4 главы)  
          - Часть 3: Галерея металлов (18 глав)
          - Часть 4: Металлы вокруг нас (6 глав)
          - Часть 5: Практика и будущее (6 глав)
          
          Всего: **42 главы** с полным содержанием и иллюстрациями.
          
          > Книга предназначена для подростков и всех, кто интересуется металлургией и материаловедением.
        draft: false
        prerelease: false
    
    - name: Upload EPUB to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/little-book-of-metals-ru.epub
        asset_name: little-book-of-metals-ru.epub
        asset_content_type: application/epub+zip
    
    - name: Upload MOBI to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/little-book-of-metals-ru.mobi
        asset_name: little-book-of-metals-ru.mobi
        asset_content_type: application/x-mobipocket-ebook