name: Сборка и развёртывание Jekyll сайта на GitHub Pages

on:
  # Запускается при пуше в основную ветку
  push:
    branches: ["main"]

  # Позволяет запускать workflow вручную из вкладки Actions
  workflow_dispatch:

# Устанавливает разрешения GITHUB_TOKEN для развёртывания на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Позволяет только одно параллельное развёртывание, пропуская запуски в очереди между уже выполняющимся и последним в очереди.
# Однако НЕ отменяет уже выполняющиеся развёртывания, так как мы хотим, чтобы эти продакшн развёртывания завершились.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Задача сборки
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Настройка Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      
      - name: Настройка Pages
        id: pages
        uses: actions/configure-pages@v4
      
      - name: Сборка с Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      
      - name: Загрузка артефакта
        uses: actions/upload-pages-artifact@v3

  # Задача развёртывания
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Развёртывание на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4